services:
  backend:
    build:
      context: ./mern/backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    networks:
        - mern-network 
    depends_on:
      - mongodb
  frontend:
      build:
        context: ./mern/frontend
        dockerfile: Dockerfile
      ports:
        - "5173:5173"
      networks:
        - mern-network
      depends_on:
        - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-network
    volumes:
      - mongodb_data:/data/db     
    
networks:
  mern-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local